import React from "react";
import "./DataPrivacy.css";

const DataPrivacy = () => {
  return (
    <div>
      <div className="termsContainer container">
        <h1>DATA PRIVACY POLICY</h1>
        <div className="underLine"></div>
        <div className="conditionContainer">
          <h1>DATA PRIVACY POLICY: HABOT MARKETPLACE</h1>
          <h3>1. Introduction</h3>
          <p>
            Welcome to <b> Varal Consultancy DMCC.</b> <br />
            <b> Varal Consultancy DMCC.</b>(“us”, “we”, or “our”) operates{" "}
            <b>habot marketplace</b> (hereinafter referred to as{" "}
            <b>“Service”</b> or <b>“Habot”</b> ). <br />
            Our Privacy Policy governs your visit to <b>habot website</b>, and
            explains how we collect, safeguard and disclose information that
            results from your use of our Service. <br />
            We use your data to provide and improve Service. By using Service,
            you agree to the collection and use of information in accordance
            with this policy. Unless otherwise defined in this Privacy Policy,
            the terms used in this Privacy Policy have the same meanings as in
            our Terms and Conditions. Our Terms and Conditions ( <b>
              “Terms”
            </b>{" "}
            ) govern all use of our Service and together with the Privacy Policy
            constitutes your agreement with us ( <b>“agreement”</b> ).
          </p>
          <br />
          <br />
          <h3>2. Definitions</h3>
          <b>2.1. SERVICE</b>
          <p> Means the habot.io website operated by Varal Consultancy DMCC.</p>
          <b>2.2. PERSONAL DATA</b>
          <p>
            {" "}
            Means any data relating to an identified natural person, or one who
            can be identified directly or indirectly by way of linking data,
            using identifiers such as name, voice, picture, identification
            number, online identifier, geographic location, or one or more
            special features that express the physical, psychological, economic,
            cultural or social identity of such person. It also includes
            Sensitive Personal Data and Biometric Data. 2.3. USAGE DATA is data
            collected automatically either generated by the use of Service or
            from Service infrastructure itself (for example, the duration of a
            page visit).
          </p>
          <h3> 2.3. USAGE DATA</h3> is data collected automatically either
          generated by the use of Service or from Service infrastructure itself
          (for example, the duration of a page visit).
          <h3>2.4. COOKIES</h3>
          <p>
            Are small files stored on your device (computer or mobile device).
          </p>
          <h3>2.5. DATA CONTROLLER</h3>{" "}
          <p>
            Is an establishment or natural person who has Personal Data and who,
            given the nature of his/her activity, specifies the method, criteria
            and purpose of Processing such Personal Data, whether individually
            or jointly with other persons or establishments 2.6. DATA PROCESSOR
            (OR SERVICE PROVIDER) is an establishment or natural person who
            processes Personal Data on behalf of the Controller, as directed and
            instructed by the Controller.
          </p>
          <h3>2.6. DATA PROCESSOR (OR SERVICE PROVIDER)</h3> Is an establishment
          or natural person who processes Personal Data on behalf of the
          Controller, as directed and instructed by the Controller.
          <h3>2.7. DATA SUBJECT</h3>{" "}
          <p>
            Is any living individual who is the subject of Personal Data. 2.8.
            USER is the individual using our Service. The User corresponds to
            the Data Subject, who is the subject of Personal Data.
          </p>
          <br />
          <br />
          <h3>3. Data Collection and Use</h3>
          <p>
            We collect several different types of information for various
            purposes to provide and improve our Service to you.
          </p>
          <br />
          <br />
          <h3> 4. Types of Data Collected</h3>
          <b>4.1. Personal Data</b> <br />
          <b>4.1.1.</b> While using our Service, we may ask you to provide us
          with certain personally identifiable information that can be used to
          contact or identify you (<b>“Personal Data”</b> ). Personally
          identifiable information may include, but is not limited to: <br />
          {"a)"} Email address <br />
          {"b)"} First name and last name <br />
          {"c)"} Phone number <br />
          {"d)"} Address, Country, State, Province, ZIP/Postal code, City <br />
          {"e)"} Cookies and Usage Data
          <br />
          <br />
          <b>4.1.2.</b> We may use your Personal Data to contact you with
          newsletters, marketing or promotional materials and other information
          that may be of interest to you. You may opt out of receiving any, or
          all, of these communications from us by following the unsubscribe
          link.
          <h3>4.2. Data from Integrated Services </h3>
          <b>4.2.1.</b> If you decide to register through or otherwise grant
          access to a Third Party “Integrated Service” such as Google, we may
          also collect Personal Data that is already associated with your
          Integrated Services account. <br /> <br />
          <b>4.2.2.</b> If you choose to provide such information during
          registration, you are giving Habot the permission to use, share and
          store it in a manner consistent with this Privacy Policy.
          <br />
          <br />
          <b>4.3 Usage Data</b> <br />
          <br />
          <b>4.3.1.</b> We may also collect information that your browser sends
          whenever you visit our Service or when you access Service by or
          through any device (<b>“Usage Data”</b> ).
          <br />
          <br />
          <b>4.3.2.</b> This Usage Data may include information such as your
          computer’s Internet Protocol address (e.g. IP address), browser type,
          browser version, the pages of our Service that you visit, the time and
          date of your visit, the time spent on those pages, unique device
          identifiers and other diagnostic data.
          <br />
          <br />
          <b>4.3.3.</b> When you access Service with a device, this Usage Data
          may include information such as the type of device you use, your
          device unique ID, the IP address of your device, your device operating
          system, the type of Internet browser you use, unique device
          identifiers and other diagnostic data.
          <br />
          <br />
          <b>4.4.Location Data</b>
          <br />
          <br />
          <b>4.4.1.</b> We may use and store information about your location if
          you give us permission to do so (<b>“Location Data”</b> ). We use this
          data to provide features of our Service, to improve and customize our
          Service.
          <br />
          <br />
          <b>4.4.2.</b> You can enable or disable location services when you use
          our Service at any time by way of your device settings.
          <br />
          <br />
          <b>4.5.Tracking Cookies Data</b> <br />
          <b>4.5.1.</b> We use cookies and similar tracking technologies to
          track the activity on our Service and we hold certain information.{" "}
          <br />
          <br />
          <b>4.5.2.</b> Cookies are files with a small amount of data which may
          include an anonymous unique identifier. Cookies are sent to your
          browser from a website and stored on your device. Other tracking
          technologies are also used such as beacons, tags and scripts to
          collect and track information and to improve and analyze our Service.
          <br />
          <br />
          <b>4.5.3.</b> You can instruct your browser to refuse all cookies or
          to indicate when a cookie is being sent. However, if you do not accept
          cookies, you may not be able to use some portions of our Service.{" "}
          <br />
          <br />
          Examples of Cookies we use: <br />
          <b>{"a)"} Session Cookies:</b> We use Session Cookies to operate our
          Service. <br />
          <b>{"b)"} Preference Cookies:</b> We use Preference Cookies to
          remember your preferences and various settings. <br />
          <b>{"b)"} Security Cookies:</b> We use Security Cookies for security
          purposes.
          <br />
          <b>{"b)"} Advertising Cookies:</b>
          Advertising Cookies are used to serve you with advertisements that may
          be relevant to you and your interests.
          <br />
          <br />
          <b>4.6.</b> Other Data While using our Service, we may also collect
          the following information: sex, age, date of birth, place of birth,
          passport details, citizenship, registration at place of residence and
          actual address, telephone number (work, mobile), details of documents
          on education, qualification, professional training, employment
          agreements, NDA agreements, information on marital status, family
          members, social security (or other taxpayer identification) number,
          office location and other data.
          <br />
          <br />
          <h3> 5. Use of Data</h3>
          <b>5.1.</b> Varal Consultancy DMCC uses the collected data for various
          purposes: <br />
          <b>5.1.1.</b> to provide and maintain our Service;
          <br />
          <b>5.1.2.</b> to notify you about changes to our Service;
          <br />
          <b>5.1.3. </b> to allow you to participate in interactive features of
          our Service when you choose to do so;
          <br />
          <b>5.1.4.</b> to provide customer support;
          <br />
          <b>5.1.5.</b> to gather analysis or valuable information so that we
          can improve our Service;
          <br />
          <b>5.1.6.</b> to monitor the usage of our Service;
          <br />
          <b>5.1.7.</b> to detect, prevent and address technical issues;
          <br />
          <b>5.1.8.</b> to fulfill any other purpose for which you provide it;
          <br />
          <b>5.1.9.</b> to carry out our obligations and enforce our rights
          arising from any contracts entered into between you and us, including
          for billing and collection;
          <br />
          <b>5.1.10.</b> to provide you with notices about your account and/or
          subscription, including expiration and renewal notices,
          email-instructions, etc.;
          <br />
          <b>5.1.11.</b> to provide you with news, special offers and general
          information about other goods, services and events which we offer that
          are similar to those that you have already purchased or enquired about
          unless you have opted not to receive such information;
          <br />
          <b>5.1.12.</b> in any other way we may describe when you provide the
          information;
          <br />
          <b>5.1.13.</b> for any other purpose with your consent.
          <br />
          <br />
          <h3> 6. Retention of Data</h3>
          <b>6.1.</b> We will retain your Personal Data only for as long as is
          necessary for the purposes set out in this Privacy Policy. We will
          retain and use your Personal Data to the extent necessary to comply
          with our legal obligations (for example, if we are required to retain
          your data to comply with applicable laws), resolve disputes, and
          enforce our legal agreements and policies. <br />
          <b>6.2.</b> We will also retain Usage Data for internal analysis
          purposes. Usage Data is generally retained for a shorter period,
          except when this data is used to strengthen the security or to improve
          the functionality of our Service, or we are legally obligated to
          retain this data for longer time periods.
          <br />
          <br />
          <h3>7. Transfer of Data</h3>
          <b>7.1.</b> Your information, including Personal Data, may be
          transferred to – and maintained on – computers located outside of your
          state, province, country or other governmental jurisdiction where the
          data protection laws may differ from those of your jurisdiction.{" "}
          <br />
          <b>7.2.</b> If you are located outside the United Arab Emirates and
          choose to provide information to us, please note that we transfer the
          data, including Personal Data, to the United Arab Emirates and process
          it there.
          <br />
          <b>7.3.</b> Your consent to this Privacy Policy followed by your
          submission of such information represents your agreement to that
          transfer.
          <br />
          <b>7.4.</b> Varal Consultancy DMCC will take all the steps reasonably
          necessary to ensure that your data is treated securely and in
          accordance with this Privacy Policy and no transfer of your Personal
          Data will take place to an organization or a country unless there are
          adequate controls in place including the security of your data and
          other personal information.
          <br />
          <br />
          <h3>8. Disclosure of Data</h3>
          We may disclose the following personal information that we collect, or
          you provide:
          <br />
          <b>8.1.Disclosure for Law Enforcement.</b> <br />
          Under certain circumstances, we may be required to disclose your
          Personal Data if required to do so by law or in response to valid
          requests by public authorities. <br />
          <b>8.2. Business Transaction.</b>
          <br />
          If we or our subsidiaries are involved in a merger, acquisition or
          asset sale, your Personal Data may be transferred.
          <br />
          <b>8.3.</b> Other cases. We may disclose your information also:
          <br />
          <b>8.3.1.</b> to our subsidiaries and affiliates;
          <br />
          <b>8.3.2.</b> to contractors, service providers, and other third
          parties we use to support our business;
          <br />
          <b>8.3.3.</b> to fulfill the purpose for which you provide it;
          <br />
          <b>8.3.4.</b> for the purpose of including your company’s logo on our
          website;
          <br />
          <b>8.3.5.</b> for any other purpose disclosed by us when you provide
          the information;
          <br />
          <b>8.3.6.</b> with your consent in any other cases;
          <br />
          <b>8.3.7.</b> if we believe disclosure is necessary or appropriate to
          protect the rights, property, or safety of the Company, our customers,
          or others.
          <br />
          <br />
          <h3>9. Security of Data</h3>
          The security of your data is important to us but remember that no
          method of transmission over the Internet or method of electronic
          storage is 100% secure. While we strive to use commercially acceptable
          means to protect your Personal Data, we cannot guarantee its absolute
          security.
          <br />
          <br />
          <h3>
            10. Your Data Protection Rights Under Federal Decree-Law no. 45 of
            2021
          </h3>
          You have the right to know that the UAE government provides data
          regulation that ultimately comprises a patchwork of various data
          provisions derived from its Penal code, Constitution, Cyber Crime Law.
          <h3>10.1. Right to obtain information</h3>
          You have the right to be told about what aspects of and how your
          Personal Data is being processed. Whilst there is no express
          requirement for businesses to use privacy notices, their use could
          assist in securing compliance with this requirement amongst others.
          <h3>10.2. Right to access</h3>
          You have the right to obtain access to your Personal Data.
          <h3>10.3. Right to request Personal Data transfer</h3>
          You have the right to request that the Personal Data is moved from one
          business to another (e.g. if they decide to change service provider).
          <h3>10.4. Right to correction or erasure</h3>
          You have the right to require inaccurate information about yourself to
          be corrected and have the right to have your Personal Data erased if
          it is no longer required for the purpose for which it was collected.
          <h3>10.5. Right to restrict or stop processing</h3>
          You may require businesses to restrict or stop processing their
          Personal Data in certain circumstances.
          <h3>10.6. Right to file a complaint</h3>
          You have the right to file a complaint with the UAE Data Office.
          <h3>10.7. Right to withdraw consent</h3>
          At any time you can withdraw consent they have given a business to
          process your Personal Data.
          <br />
          <br />
          <h3>11. Service Providers</h3>
          <b>11.1.</b> We may employ third party companies and individuals to
          facilitate our Service (<b>“Service Providers”</b> ), provide Service
          on our behalf, perform Service-related services or assist us in
          analyzing how our Service is used. <br />
          <b>11.2. </b> These third parties have access to your Personal Data
          only to perform these tasks on our behalf and are obligated not to
          disclose or use it for any other purpose. <br />
          <br />
          <h3>12. Analytics</h3>
          We may use third-party Service Providers to monitor and analyze the
          use of our Service.
          <br />
          <br />
          <h3>13. CI/CD tools</h3>
          We may use third-party Service Providers to automate the development
          process of our Service.
          <br />
          <br />
          <h3>14. Behavioral Remarketing</h3>
          We may use remarketing services to advertise on third party websites
          to you after you visited our Service. We and our third-party vendors
          use cookies to inform, optimize and serve ads based on your past
          visits to our Service.
          <br />
          <br />
          <h3>15. Payments</h3>
          <b>15.1.</b> We may provide paid products and/or services within
          Service. In that case, we use third-party services for payment
          processing (e.g. payment processors). <br />
          <b>15.2.</b> We will not store or collect your payment card details.
          That information is provided directly to our third-party payment
          processors whose use of your personal information is governed by their
          Privacy Policy. These payment processors adhere to the standards set
          by PCI-DSS as managed by the PCI Security Standards Council, which is
          a joint effort of brands like Visa, Mastercard, American Express and
          Discover. PCI-DSS requirements help ensure the secure handling of
          payment information. <br />
          <br />
          <b>16. Links to Other Sites</b> <br />
          <b>16.1.</b> Our Service may contain links to other sites that are not
          operated by us. If you click a third party link, you will be directed
          to that third party’s site. We strongly advise you to review the
          Privacy Policy of every site you visit. <br />
          <b>16.2.</b> We have no control over and assume no responsibility for
          the content, privacy policies or practices of any third party sites or
          services.
          <br />
          <br />
          <h3>17. Children’s Privacy</h3>
          <b>17.1.</b> Our Services are not intended for use by children under
          the age of 18 (<b>“Child” or “Children”</b> ). <br />
          <b>17.2.</b> We do not knowingly collect personally identifiable
          information from Children under 18. If you become aware that a Child
          has provided us with Personal Data, please contact us. If we become
          aware that we have collected Personal Data from Children without
          verification of parental consent, we take steps to remove that
          information from our servers.
          <br />
          <br />
          <h3>18. Changes to This Privacy Policy</h3>
          <b>18.1.</b> We may update our Privacy Policy from time to time. We
          will notify you of any changes by posting the new Privacy Policy on
          this page. <br />
          <b>18.2.</b> We will let you know via email and/or a prominent notice
          on our Service, prior to the change becoming effective and update
          “effective date” at the top of this Privacy Policy. <br />
          <b>18.3.</b> You are advised to review this Privacy Policy
          periodically for any changes. Changes to this Privacy Policy are
          effective when they are posted on this page. <br />
          <br />
          <br />
          <h3>19. Contact Us</h3>
          If you have any questions about this Privacy Policy, please contact us
          through our live chat.
        </div>
        <div></div>
      </div>
    </div>
  );
};

export default DataPrivacy;
